# Generated by Django 5.1.3 on 2024-11-25 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('capacidad', models.PositiveIntegerField()),
                ('es_publico', models.BooleanField(default=True)),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de entrada al evento. Déjelo en 0 para eventos gratuitos.', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('eventos', models.ManyToManyField(blank=True, related_name='categorias', to='events.evento')),
            ],
            options={
                'verbose_name_plural': 'Categorías de Eventos',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='events.ubicacion'),
        ),
        migrations.CreateModel(
            name='Registracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registrado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registraciones', to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
