# Generated by Django 5.1.3 on 2024-11-26 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de entrada al evento. Déjelo en 0 para eventos gratuitos.', max_digits=10)),
                ('ubicacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='locations.ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Registracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registrado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registraciones', to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registraciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
