# Generated by Django 5.1.3 on 2024-11-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_evento_cantidad_general_evento_cantidad_vip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, upload_to='eventos/'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.evento')),
            ],
        ),
    ]
