# Generated by Django 5.1.3 on 2024-11-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='tipodeticket',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='artista',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.DeleteModel(
            name='TipoDeTicket',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
