# Generated by Django 5.1.3 on 2024-11-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artista_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
