# Generated by Django 5.1.3 on 2024-11-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
